Du point de vue de l’utilisateur, 
le processus de recherche est semblable à la création d un enregistrement. Lorsque l’utilisateur saisit un terme dans le champ de recherche (1), 
le moteur de recherche le divise en jetons (2). 
Il associe ces jetons aux informations d’enregistrement stockées dans l’index de recherche (3), classe les enregistrements associés par pertinence (4) et 
renvoie les résultats auxquels les utilisateurs ont accès (5).

lemmatisation : regrouper des mots similaire

L’index de recherche vous donne également la possibilité d’introduire un classement de pertinence dans la préparation. C’est notre recette maison pour trouver et classer les enregistrements recherchés par les utilisateurs. 
Quels sont les ingrédients secrets ? Une pincée de **fréquence**, 
d’**ordre** et de **singularité** du terme de recherche, une noisette d'activité d’enregistrement, une cuillère de permissions d'accès et une poignée d'autres facteurs. 
Vous en avez l’eau à la bouche, n’est-ce pas ?